package puzzle.frontend.parser.dispatcher.declaration

enum class DeclarationMemberPolicy(
	val label: String,
	val allowProperty: Boolean,
	val allowFun: Boolean,
	val allowClass: Boolean,
	val allowObject: Boolean,
	val allowError: Boolean,
	val allowTrait: Boolean,
	val allowMixin: Boolean,
	val allowStruct: Boolean,
	val allowEnum: Boolean,
	val allowAnnotation: Boolean,
	val allowExtension: Boolean,
	val allowTypeAlias: Boolean,
	val allowCtor: Boolean,
	val allowNamedCtor: Boolean,
	val allowInit: Boolean,
) {
	CLASS(
		label = "类",
		allowProperty = true,
		allowFun = true,
		allowClass = true,
		allowObject = true,
		allowError = true,
		allowTrait = true,
		allowMixin = true,
		allowStruct = true,
		allowEnum = true,
		allowAnnotation = true,
		allowExtension = true,
		allowTypeAlias = true,
		allowCtor = true,
		allowNamedCtor = true,
		allowInit = true,
	),
	OBJECT(
		label = "单例对象",
		allowProperty = true,
		allowFun = true,
		allowClass = true,
		allowObject = true,
		allowError = true,
		allowTrait = true,
		allowMixin = true,
		allowStruct = true,
		allowEnum = true,
		allowAnnotation = true,
		allowExtension = true,
		allowTypeAlias = true,
		allowCtor = true,
		allowNamedCtor = true,
		allowInit = true,
	),
	STRUCT(
		label = "结构体",
		allowProperty = true,
		allowFun = true,
		allowClass = false,
		allowObject = false,
		allowError = false,
		allowTrait = false,
		allowMixin = false,
		allowStruct = false,
		allowEnum = false,
		allowAnnotation = false,
		allowExtension = false,
		allowTypeAlias = false,
		allowCtor = false,
		allowNamedCtor = false,
		allowInit = true,
	),
	TRAIT(
		label = "特征",
		allowProperty = true,
		allowFun = true,
		allowClass = true,
		allowObject = true,
		allowError = true,
		allowTrait = true,
		allowMixin = true,
		allowStruct = true,
		allowEnum = true,
		allowAnnotation = true,
		allowExtension = true,
		allowTypeAlias = true,
		allowCtor = false,
		allowNamedCtor = false,
		allowInit = false,
	),
	ENUM(
		label = "枚举",
		allowProperty = true,
		allowFun = true,
		allowClass = true,
		allowObject = true,
		allowError = true,
		allowTrait = true,
		allowMixin = true,
		allowStruct = true,
		allowEnum = true,
		allowAnnotation = true,
		allowExtension = true,
		allowTypeAlias = true,
		allowCtor = true,
		allowNamedCtor = false,
		allowInit = true,
	),
	ENUM_ENTRY(
		label = "枚举成员",
		allowProperty = true,
		allowFun = true,
		allowClass = false,
		allowObject = false,
		allowError = false,
		allowTrait = false,
		allowMixin = false,
		allowStruct = false,
		allowEnum = false,
		allowAnnotation = false,
		allowExtension = false,
		allowTypeAlias = false,
		allowCtor = false,
		allowNamedCtor = false,
		allowInit = true,
	),
	EXTENSION(
		label = "扩展",
		allowProperty = true,
		allowFun = true,
		allowClass = false,
		allowObject = false,
		allowError = false,
		allowTrait = false,
		allowMixin = false,
		allowStruct = false,
		allowEnum = false,
		allowAnnotation = false,
		allowExtension = false,
		allowTypeAlias = false,
		allowCtor = false,
		allowNamedCtor = false,
		allowInit = false,
	),
	MIXIN(
		label = "混入",
		allowProperty = true,
		allowFun = true,
		allowClass = false,
		allowObject = false,
		allowError = false,
		allowTrait = false,
		allowMixin = false,
		allowStruct = false,
		allowEnum = false,
		allowAnnotation = false,
		allowExtension = false,
		allowTypeAlias = false,
		allowCtor = false,
		allowNamedCtor = false,
		allowInit = false,
	)
}